import React, { useState } from 'react';

export default function MFASettings() {
  const [users, setUsers] = useState([
    { id: 'u1', username: 'ravi_dba', role: 'dba_senior', mfa_enabled: true, last_used: '2 mins ago' },
    { id: 'u2', username: 'priya_dba', role: 'dba_junior', mfa_enabled: true, last_used: '1 hour ago' },
    { id: 'u3', username: 'vendor_alex', role: 'vendor_support', mfa_enabled: false, last_used: 'Never' },
    { id: 'u4', username: 'admin_sara', role: 'general_admin', mfa_enabled: true, last_used: 'Yesterday' }
  ]);

  const toggleMFA = (index) => {
    const newUsers = [...users];
    newUsers[index].mfa_enabled = !newUsers[index].mfa_enabled;
    setUsers(newUsers);
  };

  return (
    <div className="card animate-in" style={{ height: '100%' }}>
      <div className="card-header">
        <div>
          <h3 className="card-title">Multi-Factor Authentication</h3>
          <div className="card-subtitle">Manage TOTP (Time-based One-Time Password) settings for database users.</div>
        </div>
      </div>

      <div style={{ padding: '20px', background: 'var(--bg-card-hover)', borderRadius: 'var(--radius-md)', marginBottom: '24px', display: 'flex', gap: '20px', alignItems: 'center' }}>
        <div style={{ fontSize: '40px' }}>📱</div>
        <div>
          <h4 style={{ fontSize: '14px', color: 'var(--text-heading)', marginBottom: '4px' }}>Authenticator App Integration</h4>
          <p style={{ fontSize: '13px', color: 'var(--text-secondary)', lineHeight: '1.5' }}>
            When the Policy Engine detects medium-risk activity (Score 40-75), it requires the user to submit a TOTP token generated by an authenticator app (Google Authenticator, Authy, etc.) before the query is allowed to execute.
          </p>
        </div>
      </div>

      <table className="data-table">
        <thead>
          <tr>
            <th>User</th>
            <th>Role</th>
            <th>MFA Status</th>
            <th>Last Used</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {users.map((user, idx) => (
            <tr key={user.id}>
              <td style={{ fontWeight: 600, color: 'var(--text-heading)' }}>{user.username}</td>
              <td>{user.role}</td>
              <td>
                <span className={`badge ${user.mfa_enabled ? 'badge-low' : 'badge-critical'}`}>
                  {user.mfa_enabled ? 'Enrolled' : 'Not Enrolled'}
                </span>
              </td>
              <td className="text-muted">{user.last_used}</td>
              <td>
                <button 
                  onClick={() => toggleMFA(idx)}
                  style={{ 
                    padding: '6px 12px', 
                    borderRadius: '4px', 
                    border: '1px solid var(--border-subtle)', 
                    background: 'var(--bg-secondary)', 
                    cursor: 'pointer',
                    fontWeight: 600,
                    color: user.mfa_enabled ? 'var(--color-critical)' : 'var(--color-accent)'
                  }}
                >
                  {user.mfa_enabled ? 'Reset TOTP' : 'Generate QR'}
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
